apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unit-converter
  template:
    metadata:
      labels:
        app: unit-converter
    spec:
      containers:
        - name: unit-converter
          image: ghcr.io/wesmosbyjr/unit-converter:7a628965b0bf9be859fcfff086d464a8d27f16fe
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000