apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit-converter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unit-converter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
      labels:
        app: unit-converter
    spec:
      containers:
        - name: unit-converter
          image: ghcr.io/wesmosbyjr/unit-converter:0b4644d75472f57645fb406d0a7bfe5368e27a24
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000