apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus-App
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-server.monitoring:80
        isDefault: false
